import { describe, it, expect } from 'vitest';
import stemWeights from '../data/shorkieStem.json';
import loci from '../data/shorkieLoci.json';
import parity from './__fixtures__/shorkieStemParity.json';
import {
  SEQ_LEN,
  IN_CHANNELS,
  N_DNA,
  N_MASK,
  N_SPECIES,
  N_BINS,
  BIN_BP,
  CROP_BP,
  CROP_BINS,
  BOTTLENECK_LEN,
  BLOCK_FILTERS,
  D_MODEL,
  N_HEADS,
  KEY_SIZE,
  VALUE_SIZE,
  N_ATTN_LAYERS,
  N_TRACKS,
  TRACK_GROUPS,
  SPECIES_S_CEREVISIAE,
  layerSpecs,
  cleanSequence,
  encodeInput,
  stemActivations,
  filterLogo,
  binToWindowOffset,
  windowOffsetToBin,
  mutate,
  type StemWeights,
} from './shorkieModel';

const stem = stemWeights as StemWeights;

describe('architecture spec, against the released f0 checkpoint', () => {
  it('input is 16,384 x 170 = 4 DNA + 1 mask + 165 species', () => {
    expect(SEQ_LEN).toBe(16384);
    expect(N_DNA + N_MASK + N_SPECIES).toBe(IN_CHANNELS);
    expect(IN_CHANNELS).toBe(170);
  });

  it('seven pooling blocks take 16,384 positions down to the 128-position bottleneck', () => {
    expect(BLOCK_FILTERS.length).toBe(7);
    expect(SEQ_LEN / 2 ** BLOCK_FILTERS.length).toBe(BOTTLENECK_LEN);
    expect(BOTTLENECK_LEN).toBe(128);
  });

  it('filter progression is the checkpoint’s, not the paper’s uniform 32-steps', () => {
    expect([...BLOCK_FILTERS]).toEqual([96, 128, 160, 192, 256, 320, 384]);
    const steps = BLOCK_FILTERS.slice(1).map((f, i) => f - BLOCK_FILTERS[i]);
    expect(steps).toEqual([32, 32, 32, 64, 64, 64]);
    expect(new Set(steps).size).toBeGreaterThan(1);
  });

  it('attention is 4 heads x 96 values = 384, and 4 heads x 64 keys = 256', () => {
    expect(N_HEADS).toBe(4);
    expect(N_HEADS * VALUE_SIZE).toBe(D_MODEL);
    expect(N_HEADS * KEY_SIZE).toBe(256);
    expect(N_ATTN_LAYERS).toBe(8);
  });

  it('three upsamples then a 64-bin crop each side gives exactly 896 bins', () => {
    expect(BOTTLENECK_LEN * 2 ** 3 - 2 * CROP_BINS).toBe(N_BINS);
    expect(N_BINS).toBe(896);
    expect(CROP_BP).toBe(1024);
    expect(N_BINS * BIN_BP).toBe(SEQ_LEN - 2 * CROP_BP);
    expect(N_BINS * BIN_BP).toBe(14336);
  });

  it('the four track groups sum to the 5,215 output channels', () => {
    expect(TRACK_GROUPS.reduce((a, g) => a + g.count, 0)).toBe(N_TRACKS);
  });

  it('layerSpecs walks stem -> 7 blocks -> 8 attention -> 3 decoder -> head', () => {
    const specs = layerSpecs();
    expect(specs).toHaveLength(1 + 7 + 8 + 3 + 1);
    expect(specs[0].positions).toBe(SEQ_LEN);
    expect(specs.at(-1)?.positions).toBe(N_BINS);
    const attn = specs.filter((s) => s.id.startsWith('attn'));
    expect(attn.every((s) => s.positions === BOTTLENECK_LEN)).toBe(true);
  });
});

describe('sequence encoding', () => {
  it('keeps only ACGT', () => {
    expect(cleanSequence('acgtNNxyz-ACGT')).toBe('ACGTACGT');
  });

  it('encodes one DNA channel and one species channel per position', () => {
    const x = encodeInput('ACGT');
    expect(x).toHaveLength(SEQ_LEN * IN_CHANNELS);
    // position 0 is 'A'
    expect(x[0]).toBe(1);
    expect(x[1]).toBe(0);
    // the mask channel is never set at inference
    for (let i = 0; i < 8; i += 1) expect(x[i * IN_CHANNELS + N_DNA]).toBe(0);
    // species one-hot is constant across positions
    const ch = N_DNA + N_MASK + SPECIES_S_CEREVISIAE;
    expect(x[ch]).toBe(1);
    expect(x[5000 * IN_CHANNELS + ch]).toBe(1);
  });

  it('positions past the sequence carry no base but still carry the species', () => {
    const x = encodeInput('AC');
    const row = 10 * IN_CHANNELS;
    expect(x[row] + x[row + 1] + x[row + 2] + x[row + 3]).toBe(0);
    expect(x[row + N_DNA + N_MASK + SPECIES_S_CEREVISIAE]).toBe(1);
  });
});

describe('conv stem', () => {
  it('ships the real 11 x 4 x 96 kernel', () => {
    expect(stem.kernelWidth).toBe(11);
    expect(stem.filters).toBe(96);
    expect(stem.weights).toHaveLength(11 * N_DNA * 96);
    expect(stem.bias).toHaveLength(96);
  });

  it('produces one valid position per kernel placement', () => {
    const seq = 'ACGT'.repeat(25); // 100 bp
    const act = stemActivations(seq, stem);
    expect(act.positions).toBe(100 - 11 + 1);
    expect(act.map).toHaveLength(96 * act.positions);
    expect(act.peak).toHaveLength(96);
  });

  it('is translation-equivariant, which is what makes the live path valid', () => {
    const core = 'GGCTATAAAAGGGCATCGAT';
    const a = stemActivations(core, stem);
    const b = stemActivations(`TTTT${core}`, stem);
    for (let f = 0; f < 96; f += 7) {
      for (let p = 0; p < a.positions; p += 1) {
        expect(b.map[f * b.positions + p + 4]).toBeCloseTo(a.map[f * a.positions + p], 5);
      }
    }
  });

  it('matches the full PyTorch model’s stem activations on a real TDH3 window', () => {
    // The fixture is generated by scripts/shorkie/make_parity_fixture.py from the checkpoint.
    const act = stemActivations(parity.sequence, stem);
    expect(act.positions).toBe(parity.validPositions);
    let compared = 0;
    parity.expected.forEach((row, fi) => {
      const f = fi * parity.filterStride;
      row.forEach((want, pi) => {
        const p = pi * parity.positionStride;
        expect(act.map[f * act.positions + p]).toBeCloseTo(want, 3);
        compared += 1;
      });
    });
    expect(compared).toBe(12 * 20);
  });

  it('reports the peak position of each filter', () => {
    const act = stemActivations(parity.sequence, stem);
    for (let f = 0; f < 96; f += 1) {
      const slice = act.map.subarray(f * act.positions, (f + 1) * act.positions);
      expect(act.peak[f]).toBeCloseTo(Math.max(...slice), 6);
      expect(slice[act.peakAt[f]]).toBeCloseTo(act.peak[f], 6);
    }
  });

  it('treats an unknown base as a zero one-hot column rather than dropping the position', () => {
    const withN = stemActivations('ACGTNACGTAC', stem);
    expect(withN.positions).toBe(1);
    expect(Number.isFinite(withN.map[0])).toBe(true);
  });
});

describe('filter logos', () => {
  it('gives one mean-centred row of four bases per kernel position', () => {
    const logo = filterLogo(0, stem);
    expect(logo).toHaveLength(11);
    logo.forEach((row) => {
      expect(row).toHaveLength(4);
      expect(row.reduce((a, b) => a + b, 0)).toBeCloseTo(0, 6);
    });
  });
});

describe('bin arithmetic', () => {
  it('round-trips bin to window offset', () => {
    for (const bin of [0, 1, 447, 895]) {
      expect(windowOffsetToBin(binToWindowOffset(bin))).toBe(bin);
    }
  });

  it('bin 0 starts after the cropped flank and the last bin ends before it', () => {
    expect(binToWindowOffset(0)).toBe(CROP_BP);
    expect(binToWindowOffset(N_BINS - 1) + BIN_BP).toBe(SEQ_LEN - CROP_BP);
  });
});

describe('mutation', () => {
  it('substitutes a single base and leaves length unchanged', () => {
    expect(mutate('ACGT', 2, 'A')).toBe('ACAT');
    expect(mutate('ACGT', 9, 'A')).toBe('ACGT');
    expect(mutate('ACGT', -1, 'A')).toBe('ACGT');
  });
});

describe('preset loci', () => {
  it('ships eight full-length windows with annotation', () => {
    expect(loci.loci.length).toBe(8);
    expect(loci.speciesIndex).toBe(SPECIES_S_CEREVISIAE);
    expect(loci.bins).toBe(N_BINS);
    loci.loci.forEach((l) => {
      expect(l.sequence).toHaveLength(SEQ_LEN);
      expect(/^[ACGTN]+$/.test(l.sequence)).toBe(true);
      expect(l.features.length).toBeGreaterThan(0);
      l.features.forEach((f) => {
        expect(f.start).toBeGreaterThanOrEqual(0);
        expect(f.end).toBeLessThanOrEqual(N_BINS);
        expect(f.end).toBeGreaterThan(f.start);
      });
    });
  });

  it('every preset contains the gene it is named for', () => {
    const wanted = ['TDH3', 'PGK1', 'ACT1', 'ADH1', 'FBA1', 'PDC1', 'GAL1', 'GAL3'];
    expect(loci.loci.map((l) => l.gene)).toEqual(wanted);
  });
});
